name: com.pywast.pywast
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+9

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.1.0+1
  intl: ^0.16.0
  shared_preferences: ^0.5.4+5
  firebase_auth: ^0.15.0+1
  google_sign_in: ^4.0.14
  flutter_facebook_login: ^3.0.0
  cloud_firestore: ^0.12.10+2
  firebase_storage: ^3.0.8
  image_picker: ^0.6.2+1
  url_launcher: ^5.2.5
  geolocator: ^5.1.5
  find_dropdown: ^0.1.7+1
  bottom_navy_bar: ^5.2.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  font_awesome_flutter: ^8.5.0
  flushbar: ^1.9.1
  shamsi_date: ^0.7.1
  cached_network_image: ^2.0.0-rc.1
  flutter_swiper: ^1.1.6
  flutter_staggered_grid_view: ^0.3.0
  rflutter_alert: ^1.0.3
  flutter_icons: ^1.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/pywast-icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AbanBold
      fonts:
        - asset: assets/fonts/Aban-Bold.ttf
    - family: BadrLight
      fonts:
        - asset: assets/fonts/Badr-light.ttf
    - family: Muna
      fonts:
        - asset: assets/fonts/Muna.ttf
    - family: MyriadReg
      fonts:
        - asset: assets/fonts/Myriad-Regular.ttf
    - family: MidanBlack
      fonts:
        - asset: assets/fonts/Midan-Black.ttf
    - family: ZarReg
      fonts:
        - asset: assets/fonts/Zar-Regular.ttf
    - family: ‌BadrBold
      fonts:
        - asset: assets/fonts/Badr-Bold.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
